spring:
   profiles:
      active:
        - dev
---
server:
  port: 8096

spring:
  profiles: dev
  application:
      name: spring-cloud-config-client-dev
info:
  app.name: microcloud-config-client-dev
  company.name: enjoy

---
server:
  port: 8096

spring:
  profiles: test
  application:
      name: spring-cloud-config-client-test
info:
  app.name: microcloud-config-client-test4
  company.name: enjoy
test: test2