spring:
   profiles:
      active:
        - dev
---
server:
  port: 8096

spring:
  profiles: dev
  application:
      name: spring-cloud-config-client-dev


---
server:
  port: 8096

spring:
  profiles: test
  application:
      name: spring-cloud-config-client-test

